a=input("Enter num 1: ")
b=input("Enter num2: ")
print("The sum is : " ,int(a)+int(b))
print("The sub is : " ,int(a)-int(b))
print("The multiply is : " ,int(a)*int(b))
print("The divison is : " ,int(a)/int(b))